### ISSUE TITLE
Delete Room from Person's Profile

### ISSUE THREAD

**Issue by JessicaDierking** [hpi-swt2/compass-portal#169]
As a user, I want to be able to delete a room from a person's profile without selecting another room so that I can change my mind later and not specify a room in the person's profile.

Acceptance:
- [ ] The user can unselect the chosen room by clicking a button
- [ ] Only persons who have the permissions to edit this person's page can remove the room

DoD
- [ ]  Tests
- [ ]  Documentation
- [ ]  CI Build passing
- [ ]  Peer Review
- [ ]  Approval from PO

**Comment by hendrix15** [comment]
Is this only about the user's own profile or also about other peoples' rooms?

**Comment by JessicaDierking** [comment]
![image](https://user-images.githubusercontent.com/68076323/150763524-87f9f80f-ad47-482f-b950-5a55a4d961a2.png)
